all:
  compiler_count: '4'
  count: 2106
  parameter_count: '395'
  version: all
develop:
  arches:
    compiler: {}
    platform:
      linux: 18670
    platform_os:
      ubuntu18.04: 18670
    target:
      x86_64: 18670
  compiler_count: '4'
  compilers:
    clang@7.0.0: 4
    gcc@6.5.0: 1
    gcc@7.5.0: 18146
    gcc@8.4.0: 519
  count: 1054
  parameter_count: '395'
  parameters:
    ARKODE: 3
    CVODE: 3
    CVODES: 3
    IDA: 3
    IDAS: 3
    KINSOL: 3
    abi: 743
    addr2line: 1
    adiak: 3
    adios2: 14
    al: 5
    amesos: 6
    amesos2: 7
    anasazi: 6
    api: 55
    app: 6
    armci: 1
    arpack: 2
    ascent: 1
    ascent_types: 11
    async_api: 11
    atomic: 30
    auto-mount: 3
    auto_swap: 1
    avx2: 16
    aztec: 6
    backend: 19
    bbapi: 11
    belos: 7
    binutils: 2
    blas: 65
    blosc: 14
    blt_find_mpi: 23
    bmi: 3
    boost: 4
    boostsys: 8
    bootstrap: 1
    bsws: 19
    build_edition: 2
    build_type: 785
    buildtype: 33
    butterflypack: 2
    bz2: 501
    bzip2: 543
    bzlib: 2
    c: 11
    c_interface: 2
    cache_base: 4
    caliper_detail: 1
    certs: 592
    ch3_rank_bits: 29
    checksum: 8
    chrono: 30
    cinema: 1
    clang: 16
    clanguage: 7
    cntl_base: 4
    column_metadata: 503
    compiler-rt: 16
    components: 22
    compression: 558
    compute: 6
    conduit: 6
    conduits: 1
    container: 9
    copy_config: 4
    cpanm: 29
    cpp: 2
    cpp14: 2
    cppflags: 2
    cross: 1
    crypto: 14
    cstd: 3
    ctypes: 501
    cuda: 39
    cuda_arch: 36
    cuda_native: 1
    curses: 519
    cxx: 36
    cxxstd: 89
    darshan: 1
    dataman: 5
    datatype-engine: 137
    date_time: 30
    dbm: 501
    debugalloc: 3
    default_library: 33
    development_files: 2
    device: 137
    device_alloc: 7
    dihydrogen: 1
    dimensions: 2
    dims: 6
    docs: 22
    double: 7
    doubleprecision: 11
    dray: 2
    dtcmp: 2
    dtype: 1
    dynamic_extensions: 503
    elf: 2
    ensurepip: 501
    epetra: 7
    epetraext: 6
    example: 7
    examples: 29
    examples-install: 3
    exception: 25
    execspace_cuda: 2
    execspace_openmp: 2
    execspace_serial: 2
    execspace_threads: 2
    exercises: 9
    explicit_template_instantiation: 6
    external_cinch: 1
    extras: 2
    fabrics: 235
    faodel: 1
    fetcher: 8
    ffmpeg: 1
    fftw: 1
    file_lock: 25
    file_systems: 29
    filesystem: 30
    flang: 1
    fonts: 8
    fortran: 256
    fpzip: 5
    ft: 9
    fts: 503
    gasnet_root: 1
    generic-math: 3
    git: 519
    glx: 11
    gmock: 2
    gobject: 9
    gold: 37
    gotcha: 3
    gotype: 7
    gpl: 2
    gptune: 2
    graph: 26
    gui: 8
    hdf5: 55
    hdf5_compat: 7
    headers: 8
    hl: 45
    host: 1
    hpctoolkit: 2
    hwloc: 139
    hydra: 137
    hypre: 7
    hzip: 5
    iconv: 14
    ifpack: 6
    ifpack2: 7
    image: 9
    instrumentation: 2
    int64: 3
    internal_unwind: 16
    intrepid: 4
    intrepid2: 4
    io: 2
    iostreams: 18
    isorropia: 4
    jpeg: 14
    kernel_lib: 1
    kim: 1
    kits: 2
    kokkos: 7
    languages: 1
    lapack: 61
    lapacke: 3
    layouts: 2
    ld: 21
    lex: 1
    lib: 7
    libbsd: 562
    libcxx: 16
    libdl: 1
    libdw: 3
    libdwarf: 2
    libiberty: 8
    libidn2: 3
    libomptarget: 2
    libs: 2224
    libsodium: 45
    libunwind: 8
    libxml2: 1378
    libyaml: 15
    libyogrt: 4
    linear_solvers: 2
    lld: 16
    lldb: 16
    llvm: 11
    llvm_dylib: 1
    locale: 20
    localstatedir: 9
    locking: 114
    log: 22
    logging: 3
    logging-level: 3
    lua: 2
    lz4: 1
    lzma: 501
    malloc: 2
    man: 1
    math: 23
    max_array_rank: 2
    max_cpu_count: 2
    max_dims: 1
    max_fields: 1
    memspace_cudaspace: 2
    memspace_cudauvmspace: 2
    metis: 14
    minitensor: 4
    ml: 6
    mlir: 1
    mpi: 313
    mpispawn: 1
    mpithreadmultiple: 6
    muelu: 7
    multibyte: 49
    multithreaded: 44
    ncurses: 30
    netaccessor: 2
    netcdf4: 4
    netmod: 137
    network: 4
    networking: 2
    nls: 22
    nox: 5
    offsets: 2
    ofi: 8
    omp_as_runtime: 13
    opengl: 17
    opengl2: 5
    openmp: 85
    openmp_blas: 4
    openpmd: 6
    openssl: 64
    optimize: 827
    ordinals: 2
    otf2: 2
    outlev: 1
    output_level: 1
    ownlibs: 22
    papi: 6
    paraview: 1
    parmetis: 14
    patches: 1813
    pci: 358
    pdf: 9
    pdsh: 2
    pdt: 2
    perf: 7
    perl: 1
    petsc: 1
    pfe: 1
    phalanx: 4
    pic: 1959
    piro: 4
    plots: 2
    plugins: 21
    pmi: 137
    pmi_backwards_compatibility: 60
    pnetcdf: 1
    png: 18
    polly: 16
    precision: 20
    process_managers: 29
    profiling: 7
    program_options: 24
    programs: 558
    psatd: 6
    pthreads: 5
    pyexpat: 501
    python: 22
    python3: 2
    pythoncmd: 501
    qed: 6
    qt: 5
    raja: 2
    random: 18
    random_access: 6
    readline: 509
    redis: 2
    regcache: 29
    regex: 23
    rendering: 11
    resource_manager: 4
    rol: 4
    romio: 194
    rsh: 57
    rtree: 503
    rythmos: 4
    sacado: 6
    sampler: 3
    scalars: 2
    scamac: 1
    scheduler: 10
    schedulers: 57
    scr: 1
    scr_config: 4
    serial: 21
    serialization: 25
    serializer: 3
    serve: 19
    shards: 4
    shared: 2917
    shylu: 4
    signals: 18
    sigsegv: 8
    silo: 3
    simmodsuite: 1
    simmodsuite_version_check: 1
    single_header: 2
    skip-tcsetpgrp-test: 4
    sm: 8
    spath: 3
    sql: 6
    sqlalchemy: 2
    sqlite3: 501
    ssc: 13
    ssh: 5
    ssl: 507
    sst: 13
    stack_size: 1
    stackguard: 7
    stackstart: 1
    stacktrace: 5
    staging: 1
    static: 68
    static_modules: 5
    std: 7
    stk: 4
    stl: 31
    stokhos: 4
    stratimikos: 5
    subtree: 1
    superlu-dist: 11
    symbol_suffix: 114
    symbols: 1
    sysconfdir: 8
    system: 37
    sz: 15
    tar: 519
    targets: 16
    tcmalloc: 3
    teko: 4
    tempus: 4
    termlib: 743
    test: 34
    testlib: 6
    tests: 35
    thread: 37
    threads: 172
    thyra: 5
    timer: 35
    tls: 31
    tm: 11
    toml: 8
    tools: 63
    tpetra: 7
    tprof: 6
    tracing: 20
    transcoder: 2
    trilinos: 1
    trilinoscouplings: 4
    umpire: 2
    unifyfs: 1
    use_vtkm: 2
    utf: 39
    uuid: 501
    veloc: 1
    version3: 2
    version_suffix: 16
    viewer: 1
    visibility: 44
    visit: 1
    vt: 57
    vtkh: 4
    vtkm: 1
    wave: 18
    weak_backtrace: 22
    wrapper: 3
    wrapper-rpath: 57
    wrapperrpath: 37
    xar: 14
    xz: 539
    zfp: 17
    zip: 522
    zlib: 528
    zoltan: 4
    zoltan2: 4
  version: '6'
v0.18:
  arches:
    compiler: {}
    platform:
      linux: 18635
    platform_os:
      ubuntu18.04: 18635
    target:
      x86_64: 18635
  compiler_count: '4'
  compilers:
    clang@7.0.0: 4
    gcc@6.5.0: 1
    gcc@7.5.0: 18111
    gcc@8.4.0: 519
  count: 1052
  parameter_count: '395'
  parameters:
    ARKODE: 3
    CVODE: 3
    CVODES: 3
    IDA: 3
    IDAS: 3
    KINSOL: 3
    abi: 742
    addr2line: 1
    adiak: 3
    adios2: 14
    al: 5
    amesos: 6
    amesos2: 7
    anasazi: 6
    api: 55
    app: 6
    armci: 1
    arpack: 2
    ascent: 1
    ascent_types: 11
    async_api: 11
    atomic: 30
    auto-mount: 3
    auto_swap: 1
    avx2: 16
    aztec: 6
    backend: 19
    bbapi: 11
    belos: 7
    binutils: 1
    blas: 65
    blosc: 14
    blt_find_mpi: 23
    bmi: 3
    boost: 4
    boostsys: 8
    bootstrap: 1
    bsws: 19
    build_edition: 2
    build_type: 785
    buildtype: 33
    butterflypack: 2
    bz2: 500
    bzip2: 541
    bzlib: 2
    c: 11
    c_interface: 2
    cache_base: 4
    caliper_detail: 1
    certs: 591
    ch3_rank_bits: 29
    checksum: 8
    chrono: 30
    cinema: 1
    clang: 16
    clanguage: 7
    cntl_base: 4
    column_metadata: 502
    compiler-rt: 16
    components: 21
    compression: 557
    compute: 6
    conduit: 6
    conduits: 1
    container: 9
    copy_config: 4
    cpanm: 29
    cpp: 2
    cpp14: 2
    cppflags: 2
    cross: 1
    crypto: 14
    cstd: 3
    ctypes: 500
    cuda: 39
    cuda_arch: 36
    cuda_native: 1
    curses: 518
    cxx: 36
    cxxstd: 89
    darshan: 1
    dataman: 5
    datatype-engine: 136
    date_time: 30
    dbm: 500
    debugalloc: 3
    default_library: 33
    development_files: 2
    device: 136
    device_alloc: 7
    dihydrogen: 1
    dimensions: 2
    dims: 6
    docs: 21
    double: 7
    doubleprecision: 11
    dray: 2
    dtcmp: 2
    dtype: 1
    dynamic_extensions: 502
    elf: 1
    ensurepip: 500
    epetra: 7
    epetraext: 6
    example: 6
    examples: 29
    examples-install: 3
    exception: 25
    execspace_cuda: 2
    execspace_openmp: 2
    execspace_serial: 2
    execspace_threads: 2
    exercises: 9
    explicit_template_instantiation: 6
    external_cinch: 1
    extras: 2
    fabrics: 234
    faodel: 1
    fetcher: 8
    ffmpeg: 1
    fftw: 1
    file_lock: 25
    file_systems: 29
    filesystem: 30
    flang: 1
    fonts: 8
    fortran: 254
    fpzip: 5
    ft: 9
    fts: 502
    gasnet_root: 1
    generic-math: 3
    git: 518
    glx: 11
    gmock: 2
    gobject: 9
    gold: 36
    gotcha: 3
    gotype: 7
    gpl: 2
    gptune: 2
    graph: 26
    gui: 8
    hdf5: 55
    hdf5_compat: 7
    headers: 7
    hl: 45
    host: 1
    hpctoolkit: 2
    hwloc: 138
    hydra: 136
    hypre: 7
    hzip: 5
    iconv: 14
    ifpack: 6
    ifpack2: 7
    image: 9
    instrumentation: 2
    int64: 3
    internal_unwind: 16
    intrepid: 4
    intrepid2: 4
    io: 1
    iostreams: 18
    isorropia: 4
    jpeg: 14
    kernel_lib: 1
    kim: 1
    kits: 2
    kokkos: 7
    languages: 1
    lapack: 61
    lapacke: 3
    layouts: 2
    ld: 20
    lex: 1
    lib: 7
    libbsd: 561
    libcxx: 16
    libdl: 1
    libdw: 3
    libdwarf: 1
    libiberty: 7
    libidn2: 3
    libomptarget: 2
    libs: 2219
    libsodium: 45
    libunwind: 7
    libxml2: 1374
    libyaml: 15
    libyogrt: 4
    linear_solvers: 2
    lld: 16
    lldb: 16
    llvm: 11
    llvm_dylib: 1
    locale: 20
    localstatedir: 9
    locking: 114
    log: 22
    logging: 3
    logging-level: 3
    lua: 2
    lz4: 1
    lzma: 500
    malloc: 2
    man: 1
    math: 23
    max_array_rank: 2
    max_cpu_count: 2
    max_dims: 1
    max_fields: 1
    memspace_cudaspace: 2
    memspace_cudauvmspace: 2
    metis: 14
    minitensor: 4
    ml: 6
    mlir: 1
    mpi: 312
    mpispawn: 1
    mpithreadmultiple: 6
    muelu: 7
    multibyte: 49
    multithreaded: 44
    ncurses: 30
    netaccessor: 2
    netcdf4: 4
    netmod: 136
    network: 4
    networking: 2
    nls: 22
    nox: 5
    offsets: 2
    ofi: 8
    omp_as_runtime: 13
    opengl: 17
    opengl2: 5
    openmp: 85
    openmp_blas: 4
    openpmd: 6
    openssl: 64
    optimize: 826
    ordinals: 2
    otf2: 1
    outlev: 1
    output_level: 1
    ownlibs: 22
    papi: 5
    paraview: 1
    parmetis: 14
    patches: 1808
    pci: 356
    pdf: 9
    pdsh: 2
    pdt: 1
    perf: 7
    perl: 1
    petsc: 1
    pfe: 1
    phalanx: 4
    pic: 1955
    piro: 4
    plots: 2
    plugins: 20
    pmi: 136
    pmi_backwards_compatibility: 60
    pnetcdf: 1
    png: 18
    polly: 16
    precision: 20
    process_managers: 29
    profiling: 7
    program_options: 24
    programs: 557
    psatd: 6
    pthreads: 4
    pyexpat: 500
    python: 21
    python3: 2
    pythoncmd: 500
    qed: 6
    qt: 5
    raja: 2
    random: 18
    random_access: 6
    readline: 508
    redis: 2
    regcache: 29
    regex: 23
    rendering: 11
    resource_manager: 4
    rol: 4
    romio: 193
    rsh: 57
    rtree: 502
    rythmos: 4
    sacado: 6
    sampler: 3
    scalars: 2
    scamac: 1
    scheduler: 10
    schedulers: 57
    scr: 1
    scr_config: 4
    serial: 21
    serialization: 25
    serializer: 3
    serve: 19
    shards: 4
    shared: 2912
    shylu: 4
    signals: 18
    sigsegv: 8
    silo: 3
    simmodsuite: 1
    simmodsuite_version_check: 1
    single_header: 2
    skip-tcsetpgrp-test: 4
    sm: 8
    spath: 3
    sql: 6
    sqlalchemy: 2
    sqlite3: 500
    ssc: 13
    ssh: 5
    ssl: 506
    sst: 13
    stack_size: 1
    stackguard: 7
    stackstart: 1
    stacktrace: 5
    staging: 1
    static: 68
    static_modules: 5
    std: 7
    stk: 4
    stl: 31
    stokhos: 4
    stratimikos: 5
    subtree: 1
    superlu-dist: 11
    symbol_suffix: 114
    symbols: 1
    sysconfdir: 8
    system: 37
    sz: 15
    tar: 518
    targets: 16
    tcmalloc: 3
    teko: 4
    tempus: 4
    termlib: 742
    test: 34
    testlib: 6
    tests: 34
    thread: 37
    threads: 172
    thyra: 5
    timer: 35
    tls: 31
    tm: 11
    toml: 8
    tools: 63
    tpetra: 7
    tprof: 6
    tracing: 20
    transcoder: 2
    trilinos: 1
    trilinoscouplings: 4
    umpire: 2
    unifyfs: 1
    use_vtkm: 2
    utf: 39
    uuid: 500
    veloc: 1
    version3: 2
    version_suffix: 16
    viewer: 1
    visibility: 44
    visit: 1
    vt: 57
    vtkh: 4
    vtkm: 1
    wave: 18
    weak_backtrace: 21
    wrapper: 3
    wrapper-rpath: 57
    wrapperrpath: 37
    xar: 14
    xz: 536
    zfp: 17
    zip: 521
    zlib: 527
    zoltan: 4
    zoltan2: 4
  version: '6'
