all:
  compiler_count: '2'
  count: 900
  parameter_count: '213'
  version: all
develop:
  compiler_count: '1'
  compilers:
    gcc@7.3.1: 7736
  count: 300
  parameter_count: '82'
  parameters:
    abi: 270
    atomic: 21
    build_system: 5675
    build_type: 150
    bz2: 78
    bzip2: 177
    certs: 206
    chrono: 21
    column_metadata: 79
    compression: 185
    cpanm: 244
    crypt: 78
    ctypes: 78
    curses: 177
    cxx: 244
    cxxstd: 21
    date_time: 21
    dbm: 78
    dynamic_extensions: 79
    exception: 21
    fabrics: 110
    filesystem: 21
    fts: 79
    generator: 52
    git: 177
    graph: 21
    gssapi: 96
    iostreams: 21
    lex: 53
    libbsd: 79
    libs: 769
    libxml2: 367
    locale: 21
    log: 21
    lzma: 78
    math: 21
    maxk: 11
    mpi: 45
    multithreaded: 21
    ncurses: 77
    open: 165
    openssl: 102
    optimize: 281
    ownlibs: 77
    patches: 1083
    pci: 112
    pic: 470
    pmi_backwards_compatibility: 98
    program_options: 21
    programs: 185
    pyexpat: 78
    pythoncmd: 78
    random: 21
    readline: 78
    regex: 21
    romio: 74
    rsh: 74
    rtree: 79
    schedulers: 74
    serialization: 21
    shared: 1075
    signals: 21
    sigsegv: 206
    sqlite3: 78
    ssl: 78
    static: 117
    stl: 244
    system: 21
    tar: 177
    termlib: 270
    test: 21
    thread: 21
    threads: 244
    timer: 21
    uuid: 78
    visibility: 21
    vt: 74
    wave: 21
    wrapper-rpath: 74
    xz: 177
    zip: 184
    zlib: 78
  version: '6'
v0.18:
  compiler_count: '2'
  compilers:
    gcc@7.3.1: 2509
    gcc@7.5.0: 1601
  count: 300
  parameter_count: '117'
  parameters:
    abi: 180
    api: 3
    atomic: 4
    blt_find_mpi: 2
    build_type: 70
    bz2: 89
    bzip2: 97
    c: 2
    certs: 114
    ch3_rank_bits: 5
    chrono: 4
    column_metadata: 94
    components: 1
    compression: 108
    container: 2
    cpanm: 148
    cpp14: 1
    ctypes: 89
    curses: 97
    cxx: 154
    cxxstd: 4
    datatype-engine: 2
    date_time: 4
    dbm: 89
    device: 2
    device_alloc: 2
    docs: 1
    dynamic_extensions: 94
    eigen: 1
    ensurepip: 89
    examples: 5
    exception: 4
    exercises: 2
    fabrics: 23
    fetcher: 3
    file_systems: 5
    filesystem: 4
    fortran: 6
    fts: 94
    git: 97
    graph: 4
    hdf5: 3
    hdf5_compat: 2
    hwloc: 2
    hydra: 2
    iostreams: 4
    legacylaunchers: 3
    lex: 26
    libbsd: 94
    libs: 427
    libxml2: 202
    locale: 4
    log: 4
    lua: 1
    lzma: 89
    math: 4
    maxk: 1
    mpi: 10
    multibyte: 1
    multithreaded: 4
    ncurses: 28
    netmod: 2
    openmp: 5
    openssl: 10
    optimize: 188
    ownlibs: 28
    parmetis: 2
    patches: 586
    pci: 16
    pic: 380
    pmi: 2
    pmi_backwards_compatibility: 8
    process_managers: 5
    program_options: 4
    programs: 108
    pyexpat: 89
    pythoncmd: 89
    raja: 1
    random: 4
    readline: 89
    regcache: 5
    regex: 4
    romio: 8
    rsh: 6
    rtree: 94
    schedulers: 6
    serialization: 4
    shared: 631
    signals: 4
    sigsegv: 64
    sqlite3: 89
    ssl: 89
    static: 6
    stl: 153
    system: 4
    tar: 97
    termlib: 180
    test: 6
    tests: 3
    thread: 4
    threads: 153
    timer: 4
    tls: 5
    toml: 10
    tools: 4
    umpire: 1
    utf: 1
    uuid: 89
    visibility: 4
    vt: 6
    wave: 4
    weak_backtrace: 1
    wrapper-rpath: 6
    wrapperrpath: 5
    xz: 98
    zip: 103
    zlib: 89
  version: '6'
v0.19:
  compiler_count: '1'
  compilers:
    gcc@7.3.1: 7493
  count: 300
  parameter_count: '198'
  parameters:
    ARKODE: 2
    CVODE: 2
    CVODES: 2
    IDA: 2
    IDAS: 2
    KINSOL: 2
    abi: 222
    adiak: 1
    api: 17
    ascent_types: 3
    atomic: 4
    avx2: 3
    blosc: 2
    blt_find_mpi: 5
    bootstrap: 2
    bsws: 3
    build: 2
    build_system: 7493
    build_type: 287
    buildtype: 3
    bz2: 106
    bzip2: 132
    bzlib: 3
    c: 2
    ccitt: 1
    certs: 159
    chrono: 5
    clanguage: 2
    column_metadata: 107
    compile_type: 1
    components: 6
    compression: 140
    container: 3
    cpanm: 211
    crypto: 5
    cstd: 2
    ctypes: 106
    curses: 130
    cxx: 214
    cxxstd: 12
    datatype-engine: 1
    date_time: 4
    dbm: 106
    default_library: 3
    device: 1
    device_alloc: 2
    docs: 6
    double: 3
    doubleprecision: 3
    dynamic_extensions: 107
    eigen: 1
    example: 2
    examples: 7
    examples-install: 2
    exception: 8
    fabrics: 136
    fetcher: 5
    ffmpeg: 2
    filesystem: 7
    fill: 1
    fortran: 31
    fpic: 3
    fpzip: 2
    fts: 107
    fv: 1
    generic-math: 2
    git: 130
    gl: 1
    glx: 3
    gotcha: 1
    gpl: 3
    graph: 7
    gssapi: 77
    hdf5: 6
    hdf5_compat: 2
    hl: 11
    hwloc: 2
    hydra: 1
    hypre: 4
    hzip: 2
    iconv: 4
    iostreams: 5
    jemalloc_prefix: 1
    jpeg: 5
    kim: 2
    lammps_sizes: 2
    languages: 2
    legacylaunchers: 21
    lex: 73
    lib: 2
    libbsd: 113
    libcurl: 1
    libdeflate: 1
    libdw: 1
    libs: 660
    libsodium: 5
    libunwind: 1
    libxml2: 318
    libyaml: 4
    locale: 4
    locking: 15
    log: 4
    logging-level: 2
    logging-mpi: 2
    logluv: 1
    lzma: 106
    lzw: 1
    man: 1
    math: 5
    maxk: 1
    metis: 5
    mpi: 80
    multibyte: 2
    multithreaded: 8
    ncurses: 110
    nesting: 1
    netmod: 1
    next: 1
    nls: 3
    opengl: 3
    openmp: 17
    openssl: 77
    opt: 1
    optimize: 237
    osmesa: 3
    ownlibs: 110
    packbits: 1
    papi: 1
    parmetis: 2
    patches: 791
    pci: 82
    perl: 1
    petsc: 1
    pic: 505
    pmi: 1
    pmi_backwards_compatibility: 76
    pnetcdf: 1
    png: 4
    precision: 11
    program_options: 5
    programs: 140
    pyexpat: 106
    pythoncmd: 106
    random: 6
    readline: 106
    regex: 6
    rendering: 3
    romio: 75
    rsh: 74
    rtree: 107
    sampler: 1
    schedulers: 74
    serial: 3
    serialization: 8
    shared: 981
    signals: 4
    sigsegv: 122
    silo: 1
    sqlite3: 106
    ssc: 2
    ssl: 106
    sst: 2
    static: 79
    stl: 212
    subtree: 1
    sundials: 1
    superlu-dist: 3
    symbol_suffix: 15
    system: 7
    sz: 2
    tar: 130
    termlib: 222
    test: 7
    testlib: 3
    tests: 8
    thread: 5
    threads: 226
    thunder: 1
    timer: 8
    tls: 8
    tm: 1
    toml: 9
    tools: 17
    utilities: 2
    uuid: 106
    version3: 3
    visibility: 8
    vt: 74
    vtkh: 1
    wave: 4
    weak_backtrace: 6
    wrapper-rpath: 74
    xar: 4
    xz: 134
    zfp: 2
    zip: 132
    zlib: 110
    zstd: 6
  version: '6'
