compiler_count: '16'
compilers:
  apple-clang@12.0.0: 330
  gcc@10.3.0: 12895
  gcc@4.8.5: 824
  gcc@6.4.0: 1132
  gcc@7.3.0: 154730
  gcc@7.3.1: 11032
  gcc@7.4.0: 5741
  gcc@7.5.0: 201342
  gcc@8.1.0: 166110
  gcc@8.2.1: 52
  gcc@8.3.1: 207452
  gcc@8.4.0: 298
  gcc@8.4.1: 13843
  gcc@9.3.0: 260626
  intel@19.1.3.304: 1064
  xl@16.1: 223
count: 63,099
parameters:
  ARKODE: 320
  CVODE: 320
  CVODES: 320
  IDA: 320
  IDAS: 320
  KINSOL: 320
  X: 102
  abi: 19078
  abs_tol: 9
  adiak: 328
  adios2: 1016
  amd_gpu_arch: 248
  amdgpu_target: 4525
  amesos: 1238
  amesos2: 1249
  analysis: 4
  anasazi: 1238
  api: 6612
  app: 569
  armci: 240
  arpack: 319
  ascent: 1
  ascent_types: 346
  async_api: 973
  atomic: 5738
  atrig_erf: 8
  auto-mount: 293
  auto_swap: 4
  avx2: 1967
  aztec: 1238
  backend: 1462
  belos: 1249
  binutils: 317
  blas: 2065
  blosc: 1627
  bmi: 789
  boost: 1249
  boostsys: 1108
  bootstrap: 14
  bsws: 2116
  build_type: 65694
  buildtype: 180
  butterflypack: 493
  bz2: 28012
  bzip2: 31386
  c: 797
  c_interface: 502
  cache_base: 369
  cairo: 1
  caliper_detail: 61
  callpath: 169
  checksum: 520
  chrono: 5738
  cinch: 296
  clang: 187
  clanguage: 1487
  clippy: 4
  cntl_base: 369
  column_metadata: 25795
  compiler-rt: 187
  complex: 1540
  compression: 12
  compute: 569
  conduit: 20
  conduits: 14
  copy_config: 369
  cpanm: 3379
  cpp14: 270
  cpu_target: 183
  cross: 367
  crypto: 9
  ctypes: 28012
  cub: 92
  cuda: 1434
  cuda_arch: 13783
  curses: 28717
  cxx: 1595
  cxx_exceptions: 32
  cxxstd: 9149
  dataman: 358
  date_time: 5738
  dbm: 28012
  default_library: 166
  device: 24559
  dimensions: 186
  dims: 569
  dll-interface: 2
  dlopen: 61
  doc: 23
  double: 3031
  double-precision: 2
  doubleprecision: 644
  dtcmp: 369
  dtk: 94
  elf: 38
  epetra: 1238
  epetraext: 1238
  example: 1126
  examples: 1313
  examples-c: 192
  examples-f77: 192
  examples-install: 320
  exception: 5738
  execspace_cuda: 156
  execspace_openmp: 156
  execspace_serial: 156
  execspace_threads: 156
  execute: 576
  exercises: 422
  exodus: 1241
  explicit_template_instantiation: 1249
  external_cinch: 61
  extra_targets: 4
  extras: 766
  fabrics: 16135
  fc: 72
  fflags: 223
  fftw: 40
  fgfs: 6
  file_lock: 737
  filesystem: 5738
  flang: 129
  float: 1544
  fonts: 232
  fortran: 29720
  ft: 199
  fts: 27908
  gasnet_root: 20
  gd: 1
  generic-math: 320
  git: 28717
  glm: 1217
  glx: 1149
  gmock: 258
  gobject: 72
  gold: 1288
  gotcha: 336
  gotype: 1238
  gpfs: 291
  gpu_arch: 40
  graph: 5738
  gtest: 1249
  gui: 98
  gzstream: 24
  hdf5: 7160
  hdf5_compat: 1125
  headers: 1093
  hip: 5
  hl: 4513
  host: 92
  host_arch: 40
  hpctoolkit: 555
  https: 8
  hwloc: 21776
  hydra: 24559
  hypre: 2804
  ifpack: 1238
  ifpack2: 1249
  image: 252
  instrumentation: 283
  int64: 110
  internal-amrex: 2
  internal_glib: 1
  internal_unwind: 202
  intrepid2: 210
  io: 317
  iostreams: 5738
  jit: 95
  jpeg: 94
  json: 8
  kernel_lib: 92
  kits: 2
  kokkos: 1249
  languages: 57
  lapack: 2065
  lapacke: 58
  layouts: 156
  ld: 270
  ldconfig: 10
  legacylaunchers: 18
  lex: 31
  lib: 569
  libbsd: 28707
  libcerf: 1
  libcxx: 200
  libdl: 20
  libdw: 167
  libdwarf: 317
  libelf: 279
  libiberty: 1093
  libomptarget: 34
  libpfm: 169
  libs: 11692
  libsodium: 3295
  libunwind: 483
  libxml2: 98117
  libyaml: 136
  libyogrt: 369
  linear_solvers: 186
  lld: 187
  lldb: 187
  llvm: 28
  llvm_dylib: 116
  locale: 5738
  localstatedir: 685
  locking: 5256
  log: 5738
  logging: 266
  long_double: 4
  lua: 362
  lz4: 273
  lzma: 28012
  malloc: 283
  man: 46
  math: 5738
  matio: 1206
  max_array_rank: 424
  max_cpu_count: 283
  max_dims: 20
  max_fields: 20
  maxdims: 71
  maxvars: 71
  memspace_cudaspace: 156
  memspace_cudauvmspace: 156
  metis: 3052
  ml: 1238
  mlir: 5
  module: 5
  mpc: 12
  mpfr: 12
  mpi: 40291
  mpithreadmultiple: 569
  muelu: 1249
  multibyte: 2207
  multithread: 905
  multithreaded: 5738
  mumps: 1238
  ncurses: 1030
  netaccessor: 357
  netcdf: 1211
  netcdf4: 6
  netgen: 12
  netmod: 24559
  network: 286
  networking: 283
  nis: 202
  nls: 664
  nodegid: 4
  nox: 256
  oce: 12
  offsets: 156
  ofi: 1108
  openfast: 1
  opengl: 194
  opengl2: 3
  openmp: 6901
  openpmd: 569
  openssl: 1302
  opt: 5
  optimal: 121
  optimize: 54765
  ordinals: 156
  osmesa: 1132
  otf2: 317
  outlev: 92
  output_level: 20
  ownlibs: 1026
  papi: 1061
  parallel-netcdf: 32
  parmetis: 416
  patches: 105036
  pci: 43062
  pdf: 199
  pdt: 317
  perf: 152
  perl: 54
  petsc: 313
  phdf5: 1
  pic: 124126
  plots: 16
  plugins: 307
  pmi: 24577
  pnetcdf: 21
  png: 1354
  polly: 202
  precision: 1744
  procfs: 15
  prod: 2
  profiling: 791
  program_options: 5738
  programs: 1001
  psatd: 569
  pshm: 124
  pthreads: 621
  pyexpat: 28012
  python: 1576
  python-type: 2
  python3: 1
  pythoncmd: 28012
  qed: 569
  qt: 3
  raja: 362
  random: 5738
  readline: 28639
  real64: 4
  regex: 5738
  rel_tol: 9
  rendering: 649
  resource_manager: 369
  rocm: 674
  rocm-device-libs: 66
  romio: 24559
  runpath: 30
  rustfmt: 4
  sacado: 1238
  sampler: 336
  scalars: 156
  scamac: 92
  scheduler: 723
  schedulers: 333
  scr_config: 369
  segment-mmap-max: 352
  selfforward: 454
  serial: 1827
  serialization: 5738
  serve: 1271
  shards: 231
  shared: 212499
  signals: 5738
  sigsegv: 785
  silo: 5
  simd: 4
  simmodsuite: 161
  simmodsuite_version_check: 161
  single_header: 1082
  skip-tcsetpgrp-test: 544
  sm: 1108
  smp: 8
  soa: 1
  spath: 219
  sql: 91
  sqlite3: 28012
  src: 4
  ssc: 1354
  ssh: 415
  ssl: 28103
  sst: 1354
  stack_size: 95
  stackguard: 152
  staging: 273
  static: 2034
  static_modules: 407
  std: 791
  stk: 21
  stl: 1286
  stratimikos: 202
  strip: 35
  suite-sparse: 1238
  superlu: 16
  superlu-dist: 1743
  swr: 1127
  symbols: 313
  sysconfdir: 627
  system: 5738
  systemcerts: 30723
  sz: 1587
  tar: 28717
  tbb: 24
  tcmalloc: 155
  tensile_architecture: 435
  termlib: 39766
  test: 7127
  test_tol: 3
  tests: 678
  tetgen: 12
  teuchos: 1249
  thread: 5738
  thread_multiple: 18
  thread_safe: 12
  threads: 12033
  timer: 6055
  timers: 1
  tioga: 5
  tm: 1208
  toolkit: 8
  tools: 762
  tpetra: 1249
  tprof: 569
  tracing: 989
  transcoder: 585
  trilinos: 313
  umpire: 362
  unit: 1
  utf: 1872
  uuid: 19037
  verbose: 440
  viewer: 44
  visibility: 5899
  vt: 333
  vtkh: 264
  wave: 5738
  wind-utils: 10
  wrapper: 113
  wrapper-rpath: 271
  wrapperrpath: 144
  xattr: 2
  xft: 17
  xss: 17
  xz: 30954
  zfp: 2043
  zlib: 30611
  zoltan: 1249
  zoltan2: 1249
version: '5'
